runtime: nodejs12
service: frontend

handlers:
# Serve all static files with url ending with a file extension
- url: /(.*\..+)$
  static_files: build/\1
  upload: build/(.*\..+)$
# Catch all handler to index.html
- url: /.*
  static_files: build/index.html
  upload: build/index.html
  
env_variables:
    MYSQL_DSN: mysql:unix_socket=/cloudsql/smart-plant-1:australia-southeast1:smartplant-dbms;dbname=smart_plant
    MYSQL_USER: root
    MYSQL_PASSWORD: 'reza123'